# Generated by Django 4.1.3 on 2022-11-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event Title', models.CharField(max_length=100)),
                ('Event Description', models.TextField(max_length=2000)),
                ('date', models.DateField(verbose_name='Event Date')),
                ('Event Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
