# Generated by Django 4.1.3 on 2022-11-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event Title',
            new_name='eventTitle',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event Location',
            new_name='evtLocation',
        ),
    ]
