# Generated by Django 4.1.3 on 2022-11-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
